name: Deploy Jekyll site to Pages 2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Install dependencies for rbenv and ruby-build
      - name: Install dependencies for rbenv and ruby-build
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            zlib1g-dev \
            libreadline-dev \
            libyaml-dev \
            libsqlite3-dev \
            sqlite3 \
            libxml2-dev \
            libxslt1-dev \
            libcurl4-openssl-dev \
            software-properties-common \
            libffi-dev

      # Step 3: Install rbenv and ruby-build
      - name: Install rbenv and ruby-build
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          cd ~/.rbenv && src/configure && make -C src
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

      # Step 4: Configure rbenv in PATH
      - name: Configure rbenv
        run: |
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          source ~/.bashrc
          echo "$HOME/.rbenv/bin" >> $GITHUB_PATH
          echo "$HOME/.rbenv/plugins/ruby-build/bin" >> $GITHUB_PATH

      # Step 5: Install Ruby
      - name: Install Ruby
        run: |
          eval "$(rbenv init -)"
          rbenv install -s 3.1.4
          rbenv global 3.1.4

      # Step 6: Setup Ruby with Bundler cache
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
          bundler-cache: true

      # Step 7: Setup Pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      # Step 8: Build with Jekyll
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      # Step 9: Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages  # Ensure artifact name matches

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: build
    steps:
      # Step 1: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
